### ISSUE TITLE
msp430_library doesn't support "includes"

### ISSUE THREAD

**Issue by zlalanne** [sergiocampama/bazel-msp430#1]
The msp430_library rule doesn't support an "includes" parameter like the default bazel cc_library. This would be useful to pass header file information to applications that depend on a library.

**Comment by sergiocampama** [comment]
What kind of information are you referring to? `includes` in cc_library adds include path statements to the compilation actions (`-I`), which makes it shorter to write header imports in dependent sources (at the cost of header path collision if multiple dependencies declare a header with the same name)

having to specify the full path relative to the WORKSPACE for header imports I believe is safer in the long run...

**Comment by zlalanne** [comment]
Perhaps it is safer, but having msp430_library match the API and behavior of bazel cc_library would be useful.

Overall though sweet work on getting bazel up and running for msp430,  I'm looking at using this

**Comment by sergiocampama** [comment]
nice!

I also realized that TI deletes the old versions from the site, so the install script does not work at this time. Sadly enough, the new version does not include an OSX variant, so I can't at this moment test the changes (traveling with a mac)...

**Comment by sergiocampama** [comment]
Done.

I was looking into the wrong place for the newest compiler... but the fact that TI deletes the old versions kinda sucks :( It'd be awesome if there was a link to the latest available version for easier automation (direct link to the binaries, not the site that lists them)

**Comment by zlalanne** [comment]
TI doesn't delete these old versions. You can replace "latest" in the URL with the specific version you want.

Something like this should always exist:

http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/5_00_00_00/exports/msp430-gcc-6.2.1.16_osx.tar.bz2

**Comment by sergiocampama** [comment]
sorry about that, I was basing this on this URL which was the one I had configured before 

http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-5.3.0.224_osx.tar.bz2

still, I added an integration test that should tell me when something broke so I can take a look...
